name: Funny Icon Pack
title: null
description: null

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - contact.md
  - changelog.md
  - privacypolicy.md
